name: keep workflow alive
on:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  keepalive-workflow:
    name: Keep workflow alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
